### ISSUE TITLE
Any chance to port to sensu-go

### ISSUE THREAD

**Issue by VeselaHouba** [sensu-plugins/sensu-plugins-slack#102]
Is there any chance that this awesome plugin will be modified for sensu-go compatibility? It seems to me, that there are major changes in event structure and possibly others, so it won't be easy task.

**Comment by nixwiz** [comment]
Hello @VeselaHouba there is a Sensu Go compatible Slack handler.  It is available as an [asset via Bonsai](https://bonsai.sensu.io/assets/sensu/sensu-slack-handler) or via [it GitHub](https://github.com/sensu/sensu-slack-handler).

**Comment by VeselaHouba** [comment]
Sorry, I meant the multi-channel one. Yes, I'm currently using sensu handler from bonsai, but the multi-channel added some extra features like custom fields.

**Comment by nixwiz** [comment]
Ah, okay then.  The best course of action in that case would be to close this issue and open one as an enhancement request to the sensu go one.  It will probably get more traction there.

**Comment by trombik** [comment]
another reason you want to use this plugin is that, sensu-go assets are not portable. most of them do not release binaries other than linux and windows. let me know any assets that support linux/mips64. sparc? managing gems is not a issue because you should be using chef/ansible/puppet. the idea of sensu-go asset is going backward. they are bloated (10-20 MB) especially when you can do the same thing with a few lines of shell.

**Comment by trombik** [comment]
confirmed that `handler-slack.rb` works with `sensu-go`. `command` attribute in pipe handler should look like:

```
handler-slack.rb --json slack --map-go-event-into-ruby
```

**Comment by VeselaHouba** [comment]
Closing - I don't think anyone is willing to implement this. Anyone is welcome to send PR :)
